#include <QCommandLineParser>
#include <QCoreApplication>
#include <QFile>
#include <QProcess>
#include <QTextStream>
#include "HWI.h"

int main(int argc, char* argv[]) {
  QCoreApplication app(argc, argv);
  QCoreApplication::setApplicationName("Hardware-finder");
  QCoreApplication::setApplicationVersion("1.0");
  QCommandLineParser parser;

  parser.setApplicationDescription("CLI tool to read out hardware info.");
  parser.addHelpOption();
  parser.addVersionOption();

  QCommandLineOption targetFileOption(
      QStringList() << "t"
                    << "target-file",
      QCoreApplication::translate(
          "main", "Target <file-path> to write hardware-info to."),
      QCoreApplication::translate("main", "file-path"));
  parser.addOption(targetFileOption);

  parser.process(app);

  QString targetFile = parser.value(targetFileOption);

  QFile file(targetFile);
  if (file.open(QIODevice::ReadWrite)) {
    QTextStream stream(&file);
    stream << "Generated by Hardware-finder 1.0 \n"
           << "\nGeneral info:"
           << "\n-------------------------------------------"
           << "\n Product ID: " << HWI::productID().toLocal8Bit().constData()
           << "\n Machine ID: " << HWI::machineID().toLocal8Bit().constData()
           << "\n OS: " << HWI::os().toLocal8Bit().constData()
           << "\n Build: " << HWI::build().toLocal8Bit().constData()
           << "\n Version" << HWI::version().toLocal8Bit().constData()
           << "\n RAM: " << HWI::RAM().toLocal8Bit().constData()
           << "\n-------------------------------------------"
           << "\n\n"
           << "\nDisplay info:"
           << "\n-------------------------------------------"
           << "\nResolution: " << HWI::resolution()
           << "\nRefresh rate: " << HWI::refreshRate()
           << "\n-------------------------------------------"
           << "\n\n"
           << "\nProcessor info (CPU):"
           << "\n-------------------------------------------"
           << "\nCPU Name: " << HWI::CPUName().toLocal8Bit().constData()
           << "\nCPU Clock Speed: "
           << HWI::CPUClockSpeed().toLocal8Bit().constData()
           << "\n-------------------------------------------"
           << "\n\n"
           << "\nGraphic card info (GPU):"
           << "\n-------------------------------------------";

    for (const auto& GPU : HWI::GPUs()) {
      stream << "\nName: " << GPU.name.toLocal8Bit().constData()
             << "\nDriver version: "
             << GPU.driverVersion.toLocal8Bit().constData()
             << "\nVRAM: " << GPU.VRAM.toLocal8Bit().constData()
             << "\n-------------------------------------------";
    }
  }

  return 0;
}
