#include <QCommandLineParser>
#include <QCoreApplication>
#include <QFile>
#include <QProcess>
#include <QTextStream>
#include "wmi_api.h"

int main(int argc, char* argv[]) {
  QCoreApplication app(argc, argv);
  QCoreApplication::setApplicationName("Hardware-finder");
  QCoreApplication::setApplicationVersion("1.0");
  QCommandLineParser parser;

  parser.setApplicationDescription("CLI tool to read out hardware info.");
  parser.addHelpOption();
  parser.addVersionOption();

  QCommandLineOption targetFileOption(
      QStringList() << "t"
                    << "target-file",
      QCoreApplication::translate(
          "main", "Target <file-path> to write hardware-info to."),
      QCoreApplication::translate("main", "file-path"));
  parser.addOption(targetFileOption);

  parser.process(app);

  QString targetFile = parser.value(targetFileOption);

  QFile file(targetFile);
  WMIAPI* wmiapi = new WMIAPI();
  wmiapi->runSearch();
  if (file.open(QIODevice::ReadWrite)) {
    QTextStream stream(&file);
    stream << "Generated by Hardware-finder 1.0 \n"
           << "\nGeneral info:"
           << "\n-------------------------------------------"
           << "\n Product ID: " << wmiapi->productID()
           << "\n Machine ID: " << wmiapi->machineID()
           << "\n OS: " << wmiapi->os() << "\n Build: " << wmiapi->build()
           << "\n Version" << wmiapi->version() << "\n RAM: " << wmiapi->RAM()
           << "\n-------------------------------------------"
           << "\n\n"
           << "\nDisplay info:"
           << "\n-------------------------------------------"
           << "\nResolution: " << wmiapi->resolution()
           << "\nRefresh rate: " << wmiapi->refreshRate()
           << "\n-------------------------------------------"
           << "\n\n"
           << "\nProcessor info (CPU):"
           << "\n-------------------------------------------"
           << "\nCPU Name: " << wmiapi->CPUName()
           << "\nCPU Clock Speed: " << wmiapi->CPUClockSpeed()
           << "\n-------------------------------------------"
           << "\n\n"
           << "\nGraphic card info (GPU):"
           << "\n-------------------------------------------";

    for (const auto& GPU : wmiapi->GPUs()) {
      stream << "\nName: " << GPU.name
             << "\nDriver version: " << GPU.driverVersion
             << "\nVRAM: " << GPU.VRAM
             << "\n-------------------------------------------";
    }
  }

  return 0;
}
